import { StyleSheet } from "react-native";

export const StyleLogin = StyleSheet.create({
    MainContainer:{
        flex:1,
        gap:10
    },
    Section1:{
        flexDirection:'row',
        padding:10,
        alignItems:'center',
        justifyContent:'center',
        gap:20
    },
    ImgSection1:{
        height:250,
        width:250,
        objectFit:'contain'
    },
    Section2:{
        alignItems:'center'
    },
    TextSection2:{
        fontSize:35,
        fontWeight:600
    },
    Section3:{
        paddingHorizontal:20,
        gap:20
    },
    BtnsSection3:{
        borderWidth:1,
        flexDirection:'row',
        padding:10,
        alignItems:'center',
        justifyContent:'center',
        gap:20,
        borderRadius:10
    },
    BtnIconSection3:{
        height:30,
        width:30,
        objectFit:'contain',
    },
    BtnTextSection3:{
        fontWeight:600
    },
    Section4:{
        justifyContent:'center',
        alignItems:'center',
        gap:10,
        paddingHorizontal:20
    },
    BtnSection4:{
        paddingVertical:15,
        backgroundColor:'#ffc300',
        width:'100%',
        justifyContent:'center',
        alignItems:'center',
        borderRadius: 25
    },
    BtnTextSection4:{
        fontWeight:600,
        fontSize:16
    },
    SubSection4:{
        flexDirection:'row',
        gap:10
    },
    BtnSubSection4:{
        color:'#ffc300',
        fontWeight:600
    },
    TextSubSection4:{
        fontWeight:200
    }

});